# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:74523271b787159f760405aa27d991666aab8e4a4c59a48bab1e3696089e5f4a",
    "cas_root_digest": "0a0379f37e16e9b39c53f696ff81658b42e8063f6e14e2f75789d1998682e1ab:78",
}
