# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:f9e0148fcbce0e10aedb9b4c642071ebfdf246423a425d9da4459fa378c4226e",
    "cas_root_digest": "193ef8bb585191f49a34f19fefdbc1ebab18c3f540599e07dda1a3b0aac5401c:78",
}
