# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:ec975fa92ece191f817282d53e8a92c2f730bfb9577667dc457fd3c60c699655",
    "cas_root_digest": "ab471c83c362f62b8007934b18c9768e5059ed9783a3b75bf94ee3271347ec32:78",
}
