# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:30d1f651e792e66b293dd7ce41425a61c815e0f6cf7de6b25c5617fdd5378c5e",
    "cas_root_digest": "113362320330ebb73dc52ae04220d0b669fc1632c27bb0e649a8e94fa2209322:77",
}
