# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:9f12610c2c8516ced7200c3305ff44c6c3ecf92871b91a2cc0ee92a8d0ca3d5f",
    "cas_root_digest": "02782e92dea8a3666b3d9eb9407e97ce1b6b3a54bec136b83c9c344a07bfb53e:78",
}
