# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:077f5aa4a526a5b50dada0f994cc22c4f18620fa4a04528bf7aa2d8ccd255e40",
    "cas_root_digest": "2f5d259b64175fe057ac799234c011f591953b33a410ff735b302dd0165abc15:80",
}
