# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:699542bc103c5225db93456549142a663472dd4c7ea08938bcadb28166497685",
    "cas_root_digest": "1db2a90b46caad7f9d2c36f889b0e4aa5218b05d928f6b54e7be2ebbc1aa8333:159",
}
