# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:1918678cf0e8d5c62ce1b7dd7b45577d71ae367853d722168e19017537659c69",
    "cas_root_digest": "fe8d2e7b3476c38ce9fe3eb8fdb26441eec647584b4cea30f19f2c415fd08a4a:77",
}
