# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:425b4902ceaadeaf978c71445cb67ca79e3c151c6b5e88b7f24d4675102c61a2",
    "cas_root_digest": "572e9e8b6a5c27eb73de72f8309233123472c183fade827ed58873bd82c84352:315",
}
