# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:f13e3f6e8995d774ed8fc4c18c6b37e9fd5a986eb4894641a5c433ebcbde15ce",
    "cas_root_digest": "8b48404330eee9763d992073ebe4d871edee6302ec3c1fa7148b54962e60cad2:78",
}
