# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:aa392c890580b0a35f4469be8a0d91d8ce7fdaa70fd8e3ad1c84379c7b0cc9b8",
    "cas_root_digest": "16c01677a649e1a708586e7d7b0853a265e7bfd272d71b623db90cf284d1b17a:78",
}
