# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:2a38c37075f7cc47024d6bcdcde43b760482e1216724de93c9ff0cb7e8b9990b",
    "cas_root_digest": "b658f42cd1607e9790c35ce38fd703f96b3ceb01091cd2bc8169f56482b197d3:78",
}
