# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:5f7fc65e20b0a8520c89bc59fa3e221ab90279a01debb947790c89faf2184cc5",
    "cas_root_digest": "ad390a9d9a0649b226978d352f63a43787b45b393f3fc6995b9a608bf4301b33:77",
}
