# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:97a176fefaf382588c4580a2537071e631e9a3353c62a919327a6cd5a2cb9f2f",
    "cas_root_digest": "3ded644a2f17abd0962d0dfef6c3725a289cfb6ee5ff3b198553677e575503e9:236",
}
