# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:7037ffc48b148f6b515a90834e807fe99c0db030489f9111366891b8710da7b8",
    "cas_root_digest": "a561b6e2d3f638ff6c9cbf693ad08e30f33f9c47c393d9e0ab6abd9e9c610388:172",
}
