# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:679814efc9f5febfa035f8a99efc87a207914627fab9e518b778d3433bb52f5e",
    "cas_root_digest": "baac80a2790f6b0861891c7d9296b1c1ab16bdf632c6424d90fa2c9c707cc02c:82",
}
