# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:000f69f8c4396f037f92b61f10a8f8efeb556f96c08b72baf6c0f4d1d73807b4",
    "cas_root_digest": "cb508668c4eb3691720ea65bfd7ec4d3df5aeb452454fad513710204053be8d7:160",
}
