# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:9ab82026e69cd42af1baddf378d747422440b557232ce6d4686d17a15728c8e7",
    "cas_root_digest": "34aa803153e28dbb1ef664e443819b74a95f9e81ec1a7d4614437b40fb2582f5:160",
}
