# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:c9a4ad4828a7da0060e0b59dea1793fc84aa9058da8b03c59c05ae5d49d01b30",
    "cas_root_digest": "0e3dd125767c78ab0f4db31c92f7baf6e3efcd1489072f87cf639bf20ffd610d:238",
}
