# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:02332f09bd8e0f72eeb9dd5c6c78682e05031e8e9dcf779fd74a4ee4eaae6c80",
    "cas_root_digest": "319ac5c1b19df08faeecbcc4e67036772cf555bfe3df21cefba7afdc1eaeea93:159",
}
