# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:29e99c11d0c686af3d99b81018d836f4401f986bbc8f2d16c6b5465c52f78934",
    "cas_root_digest": "ab76285f0fd4f1ff4b05cc9aacbe90a4283fb5ffb75931c0cb318a05719784c4:77",
}
