# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:2791a25f02c58b6bb4fa08545bfaaf51ce8537bea5cf302b24cb638c5e6aff87",
    "cas_root_digest": "7363273744b40d24cc112b5a3cf4770e30e342730fc07b6dc8a331c919cbc30a:78",
}
