# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:8fdf0eab8360eacbaaad6355df78d87a9ac6c5e35d0a7e031052df2ea5d9248f",
    "cas_root_digest": "736f9eb20662af0c951d41cea6f0036c13fd2e28ebe5eb5ee74aa400f842419c:79",
}
