# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:9444d7a8c6755114d0c7736aee59c337af9d4c983c90183883ba560d392bbed8",
    "cas_root_digest": "eef90316e5f7557266a5e9abfd9e6e3695b81e9265856a4a873986222ed93538:159",
}
