load("//bootstrap:island_visibility.bzl", "BOOTSTRAP_SUBSTITUTE_VISIBILITY")
load("//rules:pkgs.bzl", "pkgs_cas_store_output")
load("//bootstrap/substitutes/linux_x86_64_pins:08bc50efe1f5798e58c31bd56915da08-gnugrep-3.12-bin.pin.bzl", _GNUGREP_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:1d287d1ed64559b7400d9f5fe7beb83a-glibc-2.42-lib.pin.bzl", _GLIBC_LIB_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:38734d7a8c12fab1fb60ccfe92c64040-binutils-wrapper-2.46.0-bin.pin.bzl", _BINUTILS_WRAPPER_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:3c3820f85558680b8b2ffd0c0b64e138-gnused-4.9-bin.pin.bzl", _GNUSED_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:5513ee5243c4795f8d5d8fb0e955fa25-gcc-wrapper-15.2.0-bin.pin.bzl", _GCC_WRAPPER_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:5672ae7d0f5d5e37805539742605eb71-gcc-15.2.0-libstdcxx.pin.bzl", _GCC_LIBSTDCXX_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:6df76e5d5fa7584ff65282adf489f80d-gmp-6.3.0-dev.pin.bzl", _GMP_DEV_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:81d1a96fa6c5b97e8f2ccbb042ef6429-patch-2.8-bin.pin.bzl", _GNUPATCH_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:99812d28da3995945304c41c2e094a74-gawk-5.4.0-bin.pin.bzl", _GAWK_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:a409531b2056d04446f79b9f181e208e-gmp-6.3.0-lib.pin.bzl", _GMP_LIB_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:a4aceeb5ec95ad973413994284e91faa-bash-5.3-bin.pin.bzl", _BASH_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:aa4c9158de9347ee0c79055121405597-mpfr-4.2.2-lib.pin.bzl", _MPFR_LIB_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:b0ff6860dbd901389437553b076f5500-gnumake-4.4.1-bin.pin.bzl", _GNUMAKE_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:bc149dc88ef9a5064ae6e2017a6349cf-gcc-15.2.0-bin.pin.bzl", _GCC_BIN_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:cd9a36628544a7bfda54b75b593e4783-binutils-2.46.0-bin.pin.bzl", _BINUTILS_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:ce9d82673934e49165879e1c7ef25739-linux-headers-6.18.7-dev.pin.bzl", _LINUX_HEADERS_DEV_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:d79d3410372a81b85838dd003c664197-glibc-2.42-dev.pin.bzl", _GLIBC_DEV_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:dc50bb4e921e0e044cc89a5f762544de-mpfr-4.2.2-dev.pin.bzl", _MPFR_DEV_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:dfbc9c5e12b63f3fbd059a09dd1e4f6c-gcc-15.2.0-dev.pin.bzl", _GCC_DEV_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:e124ac1287a1d20190a36a83c5e2017f-libmpc-1.4.0-dev.pin.bzl", _LIBMPC_DEV_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:e731f775a0217593bc1c6bc2d921fd9b-libmpc-1.4.0-lib.pin.bzl", _LIBMPC_LIB_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:f032418bfac0cf12dff29a52793f6510-findutils-4.10.0-bin.pin.bzl", _FINDUTILS_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:f3dbbf1e0ee927e0eb8805ea8c8a7940-gcc-15.2.0-libgcc.pin.bzl", _GCC_LIBGCC_PIN = "PIN")
load("//bootstrap/substitutes/linux_x86_64_pins:fbf57a5edcd17a36c4db01db66440770-coreutils-9.10-bin.pin.bzl", _COREUTILS_PIN = "PIN")

_TARGET_SYSTEM = "x86_64-linux"
_STORE = "/pkgs/store/"

_GNUGREP = "08bc50efe1f5798e58c31bd56915da08-gnugrep-3.12-bin"
_GLIBC_LIB = "1d287d1ed64559b7400d9f5fe7beb83a-glibc-2.42-lib"
_BINUTILS_WRAPPER = "38734d7a8c12fab1fb60ccfe92c64040-binutils-wrapper-2.46.0-bin"
_GNUSED = "3c3820f85558680b8b2ffd0c0b64e138-gnused-4.9-bin"
_GCC_WRAPPER = "5513ee5243c4795f8d5d8fb0e955fa25-gcc-wrapper-15.2.0-bin"
_GCC_LIBSTDCXX = "5672ae7d0f5d5e37805539742605eb71-gcc-15.2.0-libstdcxx"
_GMP_DEV = "6df76e5d5fa7584ff65282adf489f80d-gmp-6.3.0-dev"
_GNUPATCH = "81d1a96fa6c5b97e8f2ccbb042ef6429-patch-2.8-bin"
_GAWK = "99812d28da3995945304c41c2e094a74-gawk-5.4.0-bin"
_GMP_LIB = "a409531b2056d04446f79b9f181e208e-gmp-6.3.0-lib"
_BASH = "a4aceeb5ec95ad973413994284e91faa-bash-5.3-bin"
_MPFR_LIB = "aa4c9158de9347ee0c79055121405597-mpfr-4.2.2-lib"
_GNUMAKE = "b0ff6860dbd901389437553b076f5500-gnumake-4.4.1-bin"
_GCC_BIN = "bc149dc88ef9a5064ae6e2017a6349cf-gcc-15.2.0-bin"
_BINUTILS = "cd9a36628544a7bfda54b75b593e4783-binutils-2.46.0-bin"
_LINUX_HEADERS_DEV = "ce9d82673934e49165879e1c7ef25739-linux-headers-6.18.7-dev"
_GLIBC_DEV = "d79d3410372a81b85838dd003c664197-glibc-2.42-dev"
_MPFR_DEV = "dc50bb4e921e0e044cc89a5f762544de-mpfr-4.2.2-dev"
_GCC_DEV = "dfbc9c5e12b63f3fbd059a09dd1e4f6c-gcc-15.2.0-dev"
_LIBMPC_DEV = "e124ac1287a1d20190a36a83c5e2017f-libmpc-1.4.0-dev"
_LIBMPC_LIB = "e731f775a0217593bc1c6bc2d921fd9b-libmpc-1.4.0-lib"
_FINDUTILS = "f032418bfac0cf12dff29a52793f6510-findutils-4.10.0-bin"
_GCC_LIBGCC = "f3dbbf1e0ee927e0eb8805ea8c8a7940-gcc-15.2.0-libgcc"
_COREUTILS = "fbf57a5edcd17a36c4db01db66440770-coreutils-9.10-bin"

export_file(
    name = "linux_x86_64_closure",
    src = "linux_x86_64/closure.json",
    visibility = ["PUBLIC"],
)

pkgs_cas_store_output(
    name = "glibc_lib",
    manifest = "linux_x86_64/" + _GLIBC_LIB + ".cas.manifest.json",
    package_name = "glibc",
    version = "2.42",
    output = "lib",
    store_path_key = "1d287d1ed64559b7400d9f5fe7beb83a",
    store_name = "glibc-2.42-lib",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GLIBC_LIB_PIN["cas_root_digest"],
    canonical_tree_hash = _GLIBC_LIB_PIN["canonical_tree_hash"],
    runtime_store_entries = [_GLIBC_LIB],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "glibc_dev",
    manifest = "linux_x86_64/" + _GLIBC_DEV + ".cas.manifest.json",
    package_name = "glibc",
    version = "2.42",
    output = "dev",
    store_path_key = "d79d3410372a81b85838dd003c664197",
    store_name = "glibc-2.42-dev",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GLIBC_DEV_PIN["cas_root_digest"],
    canonical_tree_hash = _GLIBC_DEV_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB],
    runtime_store_entries = [_GLIBC_DEV],
    reference_inputs = [":glibc_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "linux_headers_dev",
    manifest = "linux_x86_64/" + _LINUX_HEADERS_DEV + ".cas.manifest.json",
    package_name = "linux-headers",
    version = "6.18.7",
    output = "dev",
    store_path_key = "ce9d82673934e49165879e1c7ef25739",
    store_name = "linux-headers-6.18.7-dev",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _LINUX_HEADERS_DEV_PIN["cas_root_digest"],
    canonical_tree_hash = _LINUX_HEADERS_DEV_PIN["canonical_tree_hash"],
    runtime_store_entries = [_LINUX_HEADERS_DEV],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gmp_lib",
    manifest = "linux_x86_64/" + _GMP_LIB + ".cas.manifest.json",
    package_name = "gmp",
    version = "6.3.0",
    output = "lib",
    store_path_key = "a409531b2056d04446f79b9f181e208e",
    store_name = "gmp-6.3.0-lib",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GMP_LIB_PIN["cas_root_digest"],
    canonical_tree_hash = _GMP_LIB_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB],
    runtime_store_entries = [_GLIBC_LIB, _GMP_LIB],
    runtime_inputs = [":glibc_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gmp_dev",
    manifest = "linux_x86_64/" + _GMP_DEV + ".cas.manifest.json",
    package_name = "gmp",
    version = "6.3.0",
    output = "dev",
    store_path_key = "6df76e5d5fa7584ff65282adf489f80d",
    store_name = "gmp-6.3.0-dev",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GMP_DEV_PIN["cas_root_digest"],
    canonical_tree_hash = _GMP_DEV_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB, _STORE + _GMP_LIB],
    runtime_store_entries = [_GMP_DEV],
    reference_inputs = [":gmp_lib"],
    pkg_config_paths = ["lib/pkgconfig"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "mpfr_lib",
    manifest = "linux_x86_64/" + _MPFR_LIB + ".cas.manifest.json",
    package_name = "mpfr",
    version = "4.2.2",
    output = "lib",
    store_path_key = "aa4c9158de9347ee0c79055121405597",
    store_name = "mpfr-4.2.2-lib",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _MPFR_LIB_PIN["cas_root_digest"],
    canonical_tree_hash = _MPFR_LIB_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB, _STORE + _GMP_LIB],
    runtime_store_entries = [_GLIBC_LIB, _GMP_LIB, _MPFR_LIB],
    runtime_inputs = [":gmp_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "mpfr_dev",
    manifest = "linux_x86_64/" + _MPFR_DEV + ".cas.manifest.json",
    package_name = "mpfr",
    version = "4.2.2",
    output = "dev",
    store_path_key = "dc50bb4e921e0e044cc89a5f762544de",
    store_name = "mpfr-4.2.2-dev",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _MPFR_DEV_PIN["cas_root_digest"],
    canonical_tree_hash = _MPFR_DEV_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB, _STORE + _GMP_LIB, _STORE + _MPFR_LIB],
    runtime_store_entries = [_MPFR_DEV],
    reference_inputs = [":mpfr_lib"],
    pkg_config_paths = ["lib/pkgconfig"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "libmpc_lib",
    manifest = "linux_x86_64/" + _LIBMPC_LIB + ".cas.manifest.json",
    package_name = "libmpc",
    version = "1.4.0",
    output = "lib",
    store_path_key = "e731f775a0217593bc1c6bc2d921fd9b",
    store_name = "libmpc-1.4.0-lib",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _LIBMPC_LIB_PIN["cas_root_digest"],
    canonical_tree_hash = _LIBMPC_LIB_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB, _STORE + _GMP_LIB, _STORE + _MPFR_LIB],
    runtime_store_entries = [_GLIBC_LIB, _GMP_LIB, _MPFR_LIB, _LIBMPC_LIB],
    runtime_inputs = [":mpfr_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "libmpc_dev",
    manifest = "linux_x86_64/" + _LIBMPC_DEV + ".cas.manifest.json",
    package_name = "libmpc",
    version = "1.4.0",
    output = "dev",
    store_path_key = "e124ac1287a1d20190a36a83c5e2017f",
    store_name = "libmpc-1.4.0-dev",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _LIBMPC_DEV_PIN["cas_root_digest"],
    canonical_tree_hash = _LIBMPC_DEV_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB, _STORE + _GMP_LIB, _STORE + _MPFR_LIB, _STORE + _LIBMPC_LIB],
    runtime_store_entries = [_LIBMPC_DEV],
    reference_inputs = [":libmpc_lib"],
    pkg_config_paths = ["lib/pkgconfig"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gcc_bin",
    manifest = "linux_x86_64/" + _GCC_BIN + ".cas.manifest.json",
    package_name = "gcc",
    version = "15.2.0",
    output = "bin",
    store_path_key = "bc149dc88ef9a5064ae6e2017a6349cf",
    store_name = "gcc-15.2.0-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GCC_BIN_PIN["cas_root_digest"],
    canonical_tree_hash = _GCC_BIN_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB, _STORE + _GMP_DEV, _STORE + _GMP_LIB, _STORE + _MPFR_LIB, _STORE + _LINUX_HEADERS_DEV, _STORE + _GLIBC_DEV, _STORE + _MPFR_DEV, _STORE + _LIBMPC_DEV, _STORE + _LIBMPC_LIB],
    runtime_store_entries = [_GLIBC_LIB, _GMP_LIB, _MPFR_LIB, _GCC_BIN, _LIBMPC_LIB],
    runtime_inputs = [":libmpc_lib"],
    reference_inputs = [":glibc_dev", ":gmp_dev", ":mpfr_dev", ":libmpc_dev", ":linux_headers_dev"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gcc_libgcc",
    manifest = "linux_x86_64/" + _GCC_LIBGCC + ".cas.manifest.json",
    package_name = "gcc",
    version = "15.2.0",
    output = "libgcc",
    store_path_key = "f3dbbf1e0ee927e0eb8805ea8c8a7940",
    store_name = "gcc-15.2.0-libgcc",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GCC_LIBGCC_PIN["cas_root_digest"],
    canonical_tree_hash = _GCC_LIBGCC_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB, _STORE + _GMP_DEV, _STORE + _GMP_LIB, _STORE + _MPFR_LIB, _STORE + _LINUX_HEADERS_DEV, _STORE + _GLIBC_DEV, _STORE + _MPFR_DEV, _STORE + _LIBMPC_DEV, _STORE + _LIBMPC_LIB],
    runtime_store_entries = [_GLIBC_LIB, _GCC_LIBGCC],
    runtime_inputs = [":glibc_lib"],
    reference_inputs = [":glibc_dev", ":gmp_dev", ":mpfr_dev", ":libmpc_dev", ":linux_headers_dev"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gcc_libstdcxx",
    manifest = "linux_x86_64/" + _GCC_LIBSTDCXX + ".cas.manifest.json",
    package_name = "gcc",
    version = "15.2.0",
    output = "libstdcxx",
    store_path_key = "5672ae7d0f5d5e37805539742605eb71",
    store_name = "gcc-15.2.0-libstdcxx",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GCC_LIBSTDCXX_PIN["cas_root_digest"],
    canonical_tree_hash = _GCC_LIBSTDCXX_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB, _STORE + _GMP_DEV, _STORE + _GMP_LIB, _STORE + _MPFR_LIB, _STORE + _LINUX_HEADERS_DEV, _STORE + _GLIBC_DEV, _STORE + _MPFR_DEV, _STORE + _LIBMPC_DEV, _STORE + _LIBMPC_LIB, _STORE + _GCC_LIBGCC],
    runtime_store_entries = [_GLIBC_LIB, _GCC_LIBSTDCXX, _GCC_LIBGCC],
    runtime_inputs = [":gcc_libgcc"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gcc_dev",
    manifest = "linux_x86_64/" + _GCC_DEV + ".cas.manifest.json",
    package_name = "gcc",
    version = "15.2.0",
    output = "dev",
    store_path_key = "dfbc9c5e12b63f3fbd059a09dd1e4f6c",
    store_name = "gcc-15.2.0-dev",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GCC_DEV_PIN["cas_root_digest"],
    canonical_tree_hash = _GCC_DEV_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB, _STORE + _GCC_LIBSTDCXX, _STORE + _GMP_DEV, _STORE + _GMP_LIB, _STORE + _MPFR_LIB, _STORE + _GCC_BIN, _STORE + _LINUX_HEADERS_DEV, _STORE + _GLIBC_DEV, _STORE + _MPFR_DEV, _STORE + _LIBMPC_DEV, _STORE + _LIBMPC_LIB, _STORE + _GCC_LIBGCC],
    runtime_store_entries = [_GCC_DEV],
    reference_inputs = [":gcc_bin", ":gcc_libstdcxx", ":glibc_dev", ":gmp_dev", ":mpfr_dev", ":libmpc_dev", ":linux_headers_dev"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "binutils",
    manifest = "linux_x86_64/" + _BINUTILS + ".cas.manifest.json",
    package_name = "binutils",
    version = "2.46.0",
    output = "bin",
    store_path_key = "cd9a36628544a7bfda54b75b593e4783",
    store_name = "binutils-2.46.0-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _BINUTILS_PIN["cas_root_digest"],
    canonical_tree_hash = _BINUTILS_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB],
    runtime_store_entries = [_GLIBC_LIB, _BINUTILS],
    runtime_inputs = [":glibc_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "bash",
    manifest = "linux_x86_64/" + _BASH + ".cas.manifest.json",
    package_name = "bash",
    version = "5.3",
    output = "bin",
    store_path_key = "a4aceeb5ec95ad973413994284e91faa",
    store_name = "bash-5.3-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _BASH_PIN["cas_root_digest"],
    canonical_tree_hash = _BASH_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB],
    runtime_store_entries = [_GLIBC_LIB, _BASH],
    runtime_inputs = [":glibc_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "binutils_wrapper",
    manifest = "linux_x86_64/" + _BINUTILS_WRAPPER + ".cas.manifest.json",
    package_name = "binutils-wrapper",
    version = "2.46.0",
    output = "bin",
    store_path_key = "38734d7a8c12fab1fb60ccfe92c64040",
    store_name = "binutils-wrapper-2.46.0-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _BINUTILS_WRAPPER_PIN["cas_root_digest"],
    canonical_tree_hash = _BINUTILS_WRAPPER_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB, _STORE + _BASH, _STORE + _BINUTILS],
    runtime_store_entries = [_GLIBC_LIB, _BINUTILS_WRAPPER, _BASH, _BINUTILS],
    runtime_inputs = [":binutils", ":bash"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gnumake",
    manifest = "linux_x86_64/" + _GNUMAKE + ".cas.manifest.json",
    package_name = "gnumake",
    version = "4.4.1",
    output = "bin",
    store_path_key = "b0ff6860dbd901389437553b076f5500",
    store_name = "gnumake-4.4.1-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GNUMAKE_PIN["cas_root_digest"],
    canonical_tree_hash = _GNUMAKE_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB],
    runtime_store_entries = [_GLIBC_LIB, _GNUMAKE],
    runtime_inputs = [":glibc_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "coreutils",
    manifest = "linux_x86_64/" + _COREUTILS + ".cas.manifest.json",
    package_name = "coreutils",
    version = "9.10",
    output = "bin",
    store_path_key = "fbf57a5edcd17a36c4db01db66440770",
    store_name = "coreutils-9.10-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _COREUTILS_PIN["cas_root_digest"],
    canonical_tree_hash = _COREUTILS_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB],
    runtime_store_entries = [_GLIBC_LIB, _COREUTILS],
    runtime_inputs = [":glibc_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "findutils",
    manifest = "linux_x86_64/" + _FINDUTILS + ".cas.manifest.json",
    package_name = "findutils",
    version = "4.10.0",
    output = "bin",
    store_path_key = "f032418bfac0cf12dff29a52793f6510",
    store_name = "findutils-4.10.0-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _FINDUTILS_PIN["cas_root_digest"],
    canonical_tree_hash = _FINDUTILS_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB],
    runtime_store_entries = [_GLIBC_LIB, _FINDUTILS],
    runtime_inputs = [":glibc_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gnused",
    manifest = "linux_x86_64/" + _GNUSED + ".cas.manifest.json",
    package_name = "gnused",
    version = "4.9",
    output = "bin",
    store_path_key = "3c3820f85558680b8b2ffd0c0b64e138",
    store_name = "gnused-4.9-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GNUSED_PIN["cas_root_digest"],
    canonical_tree_hash = _GNUSED_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB],
    runtime_store_entries = [_GLIBC_LIB, _GNUSED],
    runtime_inputs = [":glibc_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gnugrep",
    manifest = "linux_x86_64/" + _GNUGREP + ".cas.manifest.json",
    package_name = "gnugrep",
    version = "3.12",
    output = "bin",
    store_path_key = "08bc50efe1f5798e58c31bd56915da08",
    store_name = "gnugrep-3.12-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GNUGREP_PIN["cas_root_digest"],
    canonical_tree_hash = _GNUGREP_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB],
    runtime_store_entries = [_GNUGREP, _GLIBC_LIB],
    runtime_inputs = [":glibc_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gawk",
    manifest = "linux_x86_64/" + _GAWK + ".cas.manifest.json",
    package_name = "gawk",
    version = "5.4.0",
    output = "bin",
    store_path_key = "99812d28da3995945304c41c2e094a74",
    store_name = "gawk-5.4.0-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GAWK_PIN["cas_root_digest"],
    canonical_tree_hash = _GAWK_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB],
    runtime_store_entries = [_GLIBC_LIB, _GAWK],
    runtime_inputs = [":glibc_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gnupatch",
    manifest = "linux_x86_64/" + _GNUPATCH + ".cas.manifest.json",
    package_name = "patch",
    version = "2.8",
    output = "bin",
    store_path_key = "81d1a96fa6c5b97e8f2ccbb042ef6429",
    store_name = "patch-2.8-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GNUPATCH_PIN["cas_root_digest"],
    canonical_tree_hash = _GNUPATCH_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB],
    runtime_store_entries = [_GLIBC_LIB, _GNUPATCH],
    runtime_inputs = [":glibc_lib"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)

pkgs_cas_store_output(
    name = "gcc_wrapper",
    manifest = "linux_x86_64/" + _GCC_WRAPPER + ".cas.manifest.json",
    package_name = "gcc-wrapper",
    version = "15.2.0",
    output = "bin",
    store_path_key = "5513ee5243c4795f8d5d8fb0e955fa25",
    store_name = "gcc-wrapper-15.2.0-bin",
    target_system = _TARGET_SYSTEM,
    cas_root_digest = _GCC_WRAPPER_PIN["cas_root_digest"],
    canonical_tree_hash = _GCC_WRAPPER_PIN["canonical_tree_hash"],
    references = [_STORE + _GLIBC_LIB, _STORE + _BINUTILS_WRAPPER, _STORE + _GCC_LIBSTDCXX, _STORE + _GMP_DEV, _STORE + _GMP_LIB, _STORE + _BASH, _STORE + _MPFR_LIB, _STORE + _GCC_BIN, _STORE + _BINUTILS, _STORE + _LINUX_HEADERS_DEV, _STORE + _GLIBC_DEV, _STORE + _MPFR_DEV, _STORE + _GCC_DEV, _STORE + _LIBMPC_DEV, _STORE + _LIBMPC_LIB, _STORE + _GCC_LIBGCC],
    runtime_store_entries = [_GLIBC_LIB, _GCC_WRAPPER, _GMP_LIB, _BASH, _MPFR_LIB, _GCC_BIN, _LIBMPC_LIB],
    tool_store_entries = [_GLIBC_LIB, _BINUTILS_WRAPPER, _GCC_WRAPPER, _GCC_LIBSTDCXX, _GMP_LIB, _BASH, _MPFR_LIB, _GCC_BIN, _BINUTILS, _LINUX_HEADERS_DEV, _GLIBC_DEV, _GCC_DEV, _LIBMPC_LIB, _GCC_LIBGCC],
    runtime_inputs = [":gcc_bin", ":bash"],
    tool_inputs = [":gcc_dev", ":gcc_libstdcxx", ":binutils_wrapper", ":glibc_dev", ":linux_headers_dev"],
    visibility = BOOTSTRAP_SUBSTITUTE_VISIBILITY,
)
