load(
    "//rules:pkgs.bzl",
    "pkgs_configure_make_install_package",
    "pkgs_elf_interpreters",
    "pkgs_make_install_package",
    "pkgs_package",
    "pkgs_seed_free",
    "pkgs_source",
)

_PAYLOAD_FILE_CONTENT = ["built with a foreign input, but does not retain it"]

write_file(
    name = "payload_file",
    out = "payload",
    content = _PAYLOAD_FILE_CONTENT,
)

filegroup(
    name = "payload_tree",
    srcs = {
        "share/payload": ":payload_file",
    },
    copy = True,
)

_PAYLOAD_SOURCE = pkgs_source(
    dep = ":payload_tree",
    digests = ["sha256:" + sha256("\n".join(["share/payload"] + _PAYLOAD_FILE_CONTENT))],
)

pkgs_package(
    name = "build_only_dep",
    package_name = "build-only-dep",
    version = "0",
    builder = "bootstrap-test-v0",
    src = _PAYLOAD_SOURCE,
    native_build_inputs = ["//bootstrap/foreign_seed:bash"],
)

pkgs_seed_free(
    name = "build_only_dep_seed_free",
    packages = [":build_only_dep"],
    forbidden = ["//bootstrap/foreign_seed:bash"],
)

_CLOSURE_CONSUMER_MAKEFILE_CONTENT = [
    "all:",
    "\t:",
    "install:",
    "\tmkdir -p \"$(DESTDIR)$(PREFIX)/share\"",
    "\tprintf closure-store-output > \"$(DESTDIR)$(PREFIX)/share/payload\"",
]

write_file(
    name = "closure_consumer_makefile",
    out = "Makefile",
    content = _CLOSURE_CONSUMER_MAKEFILE_CONTENT,
)

filegroup(
    name = "closure_consumer_source",
    srcs = {
        "Makefile": ":closure_consumer_makefile",
    },
    copy = True,
)

_CLOSURE_CONSUMER_SOURCE = pkgs_source(
    dep = ":closure_consumer_source",
    digests = ["sha256:" + sha256("\n".join(["Makefile"] + _CLOSURE_CONSUMER_MAKEFILE_CONTENT))],
)

pkgs_make_install_package(
    name = "closure_consumer",
    package_name = "closure-consumer",
    version = "0",
    sources = [_CLOSURE_CONSUMER_SOURCE],
    native_build_inputs = [
        "//bootstrap/foreign_seed:coreutils",
        "//bootstrap/foreign_seed:gnumake",
    ],
)

_MULTI_SOURCE_MAKEFILE_CONTENT = [
    "all:",
    "\t:",
    "install:",
    "\tmkdir -p \"$(DESTDIR)$(PREFIX)/share\"",
    "\tcp vendor/payload \"$(DESTDIR)$(PREFIX)/share/payload\"",
]

write_file(
    name = "multi_source_makefile",
    out = "Makefile",
    content = _MULTI_SOURCE_MAKEFILE_CONTENT,
)

filegroup(
    name = "multi_source_base_tree",
    srcs = {
        "Makefile": ":multi_source_makefile",
    },
    copy = True,
)

_MULTI_SOURCE_PAYLOAD_CONTENT = ["payload from the extra source tree"]

write_file(
    name = "multi_source_payload",
    out = "payload",
    content = _MULTI_SOURCE_PAYLOAD_CONTENT,
)

filegroup(
    name = "multi_source_extra_tree",
    srcs = {
        "vendor/payload": ":multi_source_payload",
    },
    copy = True,
)

_MULTI_SOURCE_BASE = pkgs_source(
    dep = ":multi_source_base_tree",
    digests = ["sha256:" + sha256("\n".join(["Makefile"] + _MULTI_SOURCE_MAKEFILE_CONTENT))],
)

_MULTI_SOURCE_EXTRA = pkgs_source(
    dep = ":multi_source_extra_tree",
    digests = ["sha256:" + sha256("\n".join(["vendor/payload"] + _MULTI_SOURCE_PAYLOAD_CONTENT))],
)

pkgs_make_install_package(
    name = "multi_source_consumer",
    package_name = "multi-source-consumer",
    version = "0",
    sources = [
        _MULTI_SOURCE_BASE,
        _MULTI_SOURCE_EXTRA,
    ],
    native_build_inputs = [
        "//bootstrap/foreign_seed:coreutils",
        "//bootstrap/foreign_seed:gnumake",
    ],
)

_SELF_REF_CONFIGURE_CONTENT = [
    "#!/bin/sh",
    "set -eu",
    "prefix=''",
    "self_path=''",
    "for arg in \"$@\"; do",
    "  case \"$arg\" in",
    "    --prefix=*) prefix=\"${arg#--prefix=}\" ;;",
    "    --self-path=*) self_path=\"${arg#--self-path=}\" ;;",
    "  esac",
    "done",
    "cat > Makefile <<EOF",
    "PREFIX := $prefix",
    "SELF_PATH := $self_path",
    "all:",
    "\t:",
    "install:",
    "\tmkdir -p \"\\$(DESTDIR)\\$(PREFIX)/share\"",
    "\tprintf '%s' \"\\$(SELF_PATH)\" > \"\\$(DESTDIR)\\$(PREFIX)/share/self-path\"",
    "EOF",
]

write_file(
    name = "self_ref_configure",
    out = "configure",
    content = _SELF_REF_CONFIGURE_CONTENT,
    is_executable = True,
)

filegroup(
    name = "self_ref_source",
    srcs = {
        "configure": ":self_ref_configure",
    },
    copy = True,
)

_SELF_REF_SOURCE = pkgs_source(
    dep = ":self_ref_source",
    digests = ["sha256:" + sha256("\n".join(["configure"] + _SELF_REF_CONFIGURE_CONTENT))],
)

pkgs_configure_make_install_package(
    name = "self_ref_consumer",
    package_name = "self-ref-consumer",
    version = "0",
    sources = [_SELF_REF_SOURCE],
    configure_arg_self_store_paths = [
        ("--self-path=", ""),
    ],
    native_build_inputs = [
        "//bootstrap/foreign_seed:coreutils",
        "//bootstrap/foreign_seed:gnumake",
    ],
)

_FAILED_CONSUMER_MAKEFILE_CONTENT = [
    "all:",
    "\t:",
    "install:",
    "\tfalse",
]

write_file(
    name = "failed_consumer_makefile",
    out = "Makefile",
    content = _FAILED_CONSUMER_MAKEFILE_CONTENT,
)

filegroup(
    name = "failed_consumer_source",
    srcs = {
        "Makefile": ":failed_consumer_makefile",
    },
    copy = True,
)

_FAILED_CONSUMER_SOURCE = pkgs_source(
    dep = ":failed_consumer_source",
    digests = ["sha256:" + sha256("\n".join(["Makefile"] + _FAILED_CONSUMER_MAKEFILE_CONTENT))],
)

pkgs_make_install_package(
    name = "failed_consumer",
    package_name = "failed-consumer",
    version = "0",
    sources = [_FAILED_CONSUMER_SOURCE],
    native_build_inputs = [
        "//bootstrap/foreign_seed:coreutils",
        "//bootstrap/foreign_seed:gnumake",
    ],
)

_FINAL_BASE = [
    "//development/libraries/glibc:out_stage1",
    "//development/tools/misc/binutils:bin_stage1",
    "//development/compilers/gcc:out_stage2",
    "//development/tools/build-managers/gnumake:bin",
    "//shells/bash:bin",
    "//tools/archivers/gnutar:bin",
    "//tools/compression/bzip2:bin",
    "//tools/compression/gzip:out",
    "//tools/misc/coreutils:bin",
    "//tools/misc/findutils:bin",
    "//tools/text/diffutils:bin",
    "//tools/text/gawk:bin",
    "//tools/text/gnugrep:bin",
    "//tools/text/gnupatch:bin",
    "//tools/text/gnused:bin",
]

_FOREIGN_SEED = [
    "//bootstrap/foreign_seed:bash",
    "//bootstrap/foreign_seed:gnumake",
    "//bootstrap/foreign_seed:gcc",
    "//bootstrap/foreign_seed:binutils",
    "//bootstrap/foreign_seed:coreutils",
    "//bootstrap/foreign_seed:gnused",
    "//bootstrap/foreign_seed:gnugrep",
    "//bootstrap/foreign_seed:gawk",
    "//bootstrap/foreign_seed:gnum4",
    "//bootstrap/foreign_seed:bison",
    "//bootstrap/foreign_seed:gettext",
    "//bootstrap/foreign_seed:python3",
    "//bootstrap/foreign_seed:gnutar",
    "//bootstrap/foreign_seed:gzip",
    "//bootstrap/foreign_seed:patch",
    "//bootstrap/foreign_seed:diffutils",
    "//bootstrap/foreign_seed:findutils",
]

pkgs_seed_free(
    name = "final_base_seed_free",
    packages = _FINAL_BASE,
    forbidden = _FOREIGN_SEED,
)

pkgs_elf_interpreters(
    name = "final_base_pkgs_interpreters",
    packages = _FINAL_BASE,
    interpreter = "//development/libraries/glibc:out_stage1",
    interpreter_relpath = "lib/ld-linux-x86-64.so.2",
)
