load(
    "//rules:pkgs.bzl",
    "pkgs_configure_make_install_package",
    "pkgs_elf_interpreters",
    "pkgs_export_store_substitute",
    "pkgs_export_store_tree_substitute",
    "pkgs_export_patch",
    "pkgs_foreign_build_free",
    "pkgs_imported_store_output",
    "pkgs_make_install_package",
    "pkgs_package",
    "pkgs_seed_free",
    "pkgs_self_store_path",
    "pkgs_source",
)

_PAYLOAD_FILE_CONTENT = ["built with a foreign input, but does not retain it"]

write_file(
    name = "payload_file",
    out = "payload",
    content = _PAYLOAD_FILE_CONTENT,
)

filegroup(
    name = "payload_tree",
    srcs = {
        "share/payload": ":payload_file",
    },
    copy = True,
)

_PAYLOAD_SOURCE = pkgs_source(
    dep = ":payload_tree",
    digests = ["sha256:" + sha256("\n".join(["share/payload"] + _PAYLOAD_FILE_CONTENT))],
)

pkgs_package(
    name = "build_only_dep",
    package_name = "build-only-dep",
    version = "0",
    builder = "bootstrap-test-v0",
    sources = [_PAYLOAD_SOURCE],
    native_build_inputs = ["//bootstrap/foreign_seed:bash"],
)

pkgs_seed_free(
    name = "build_only_dep_seed_free",
    packages = [":build_only_dep"],
    forbidden = ["//bootstrap/foreign_seed:bash"],
)

pkgs_export_store_substitute(
    name = "build_only_dep_substitute",
    package = ":build_only_dep",
)

pkgs_imported_store_output(
    name = "build_only_dep_imported",
    substitute = ":build_only_dep_substitute",
)

pkgs_export_store_tree_substitute(
    name = "source_tree_substitute",
    tree = ":payload_tree",
    package_name = "source-tree",
    version = "0",
    store_path_key = "0123456789abcdef0123456789abcdef",
    store_name = "source-tree-0",
)

pkgs_imported_store_output(
    name = "source_tree_imported",
    substitute = ":source_tree_substitute",
)

pkgs_package(
    name = "runtime_consumer",
    package_name = "runtime-consumer",
    version = "0",
    builder = "bootstrap-test-v0",
    sources = [_PAYLOAD_SOURCE],
    runtime_inputs = [":build_only_dep"],
)

pkgs_export_store_substitute(
    name = "runtime_consumer_substitute",
    package = ":runtime_consumer",
)

pkgs_imported_store_output(
    name = "runtime_consumer_imported",
    substitute = ":runtime_consumer_substitute",
    runtime_inputs = [":build_only_dep_imported"],
)

_CLOSURE_CONSUMER_MAKEFILE_CONTENT = [
    "all:",
    "\t:",
    "install:",
    "\tmkdir -p \"$(DESTDIR)$(PREFIX)/share\"",
    "\tprintf closure-store-output > \"$(DESTDIR)$(PREFIX)/share/payload\"",
]

write_file(
    name = "closure_consumer_makefile",
    out = "Makefile",
    content = _CLOSURE_CONSUMER_MAKEFILE_CONTENT,
)

filegroup(
    name = "closure_consumer_source",
    srcs = {
        "Makefile": ":closure_consumer_makefile",
    },
    copy = True,
)

_CLOSURE_CONSUMER_SOURCE = pkgs_source(
    dep = ":closure_consumer_source",
    digests = ["sha256:" + sha256("\n".join(["Makefile"] + _CLOSURE_CONSUMER_MAKEFILE_CONTENT))],
)

pkgs_make_install_package(
    name = "closure_consumer",
    package_name = "closure-consumer",
    version = "0",
    sources = [_CLOSURE_CONSUMER_SOURCE],
    native_build_inputs = [
        "//bootstrap/foreign_seed:coreutils",
        "//bootstrap/foreign_seed:gnumake",
    ],
)

_MULTI_SOURCE_MAKEFILE_CONTENT = [
    "all:",
    "\t:",
    "install:",
    "\tmkdir -p \"$(DESTDIR)$(PREFIX)/share\"",
    "\tcp vendor/payload \"$(DESTDIR)$(PREFIX)/share/payload\"",
]

write_file(
    name = "multi_source_makefile",
    out = "Makefile",
    content = _MULTI_SOURCE_MAKEFILE_CONTENT,
)

filegroup(
    name = "multi_source_base_tree",
    srcs = {
        "Makefile": ":multi_source_makefile",
    },
    copy = True,
)

_MULTI_SOURCE_PAYLOAD_CONTENT = ["payload from the extra source tree"]

write_file(
    name = "multi_source_payload",
    out = "payload",
    content = _MULTI_SOURCE_PAYLOAD_CONTENT,
)

filegroup(
    name = "multi_source_extra_tree",
    srcs = {
        "vendor/payload": ":multi_source_payload",
    },
    copy = True,
)

_MULTI_SOURCE_BASE = pkgs_source(
    dep = ":multi_source_base_tree",
    digests = ["sha256:" + sha256("\n".join(["Makefile"] + _MULTI_SOURCE_MAKEFILE_CONTENT))],
)

_MULTI_SOURCE_EXTRA = pkgs_source(
    dep = ":multi_source_extra_tree",
    digests = ["sha256:" + sha256("\n".join(["vendor/payload"] + _MULTI_SOURCE_PAYLOAD_CONTENT))],
)

pkgs_make_install_package(
    name = "multi_source_consumer",
    package_name = "multi-source-consumer",
    version = "0",
    sources = [
        _MULTI_SOURCE_BASE,
        _MULTI_SOURCE_EXTRA,
    ],
    native_build_inputs = [
        "//bootstrap/foreign_seed:coreutils",
        "//bootstrap/foreign_seed:gnumake",
    ],
)

_PLATFORM_PATCH_MAKEFILE_CONTENT = [
    "PAYLOAD := unpatched",
    "all:",
    "\t:",
    "install:",
    "\tmkdir -p \"$(DESTDIR)$(PREFIX)/share\"",
    "\tprintf '%s' \"$(PAYLOAD)\" > \"$(DESTDIR)$(PREFIX)/share/payload\"",
]

write_file(
    name = "platform_patch_makefile",
    out = "Makefile",
    content = _PLATFORM_PATCH_MAKEFILE_CONTENT,
)

filegroup(
    name = "platform_patch_source",
    srcs = {
        "Makefile": ":platform_patch_makefile",
    },
    copy = True,
)

_PLATFORM_PATCH_SOURCE = pkgs_source(
    dep = ":platform_patch_source",
    digests = ["sha256:" + sha256("\n".join(["Makefile"] + _PLATFORM_PATCH_MAKEFILE_CONTENT))],
)

_PLATFORM_PATCH_X86_64 = pkgs_export_patch(
    name = "platform_payload_x86_64_patch",
    src = "patches/0001-platform-payload-x86_64.patch",
    sha256 = "3a387eedca306bfd36c5a0214b7a131d8decb48e45036834b893ee678dfc3440",
)

_PLATFORM_PATCH_ARM64 = pkgs_export_patch(
    name = "platform_payload_arm64_patch",
    src = "patches/0001-platform-payload-arm64.patch",
    sha256 = "04c2183de025a09144c3d02dd82ec75591a7fd67af1b7230ed6cd7b07ab89f8f",
)

pkgs_make_install_package(
    name = "platform_patch_consumer",
    package_name = "platform-patch-consumer",
    version = "0",
    sources = select({
        "//platforms:linux_arm64": [_PLATFORM_PATCH_SOURCE],
        "//platforms:linux_x86_64": [_PLATFORM_PATCH_SOURCE],
    }),
    patches = select({
        "//platforms:linux_arm64": [_PLATFORM_PATCH_ARM64],
        "//platforms:linux_x86_64": [_PLATFORM_PATCH_X86_64],
    }),
    native_build_inputs = [
        "//bootstrap/foreign_seed:coreutils",
        "//bootstrap/foreign_seed:gnumake",
        "//bootstrap/foreign_seed:patch",
    ],
)

_SELF_REF_CONFIGURE_CONTENT = [
    "#!/bin/sh",
    "set -eu",
    "prefix=''",
    "self_path=''",
    "for arg in \"$@\"; do",
    "  case \"$arg\" in",
    "    --prefix=*) prefix=\"${arg#--prefix=}\" ;;",
    "    --self-path=*) self_path=\"${arg#--self-path=}\" ;;",
    "  esac",
    "done",
    "cat > Makefile <<EOF",
    "PREFIX := $prefix",
    "SELF_PATH := $self_path",
    "all:",
    "\t:",
    "install:",
    "\tmkdir -p \"\\$(DESTDIR)\\$(PREFIX)/share\"",
    "\tprintf '%s' \"\\$(SELF_PATH)\" > \"\\$(DESTDIR)\\$(PREFIX)/share/self-path\"",
    "EOF",
]

write_file(
    name = "self_ref_configure",
    out = "configure",
    content = _SELF_REF_CONFIGURE_CONTENT,
    is_executable = True,
)

filegroup(
    name = "self_ref_source",
    srcs = {
        "configure": ":self_ref_configure",
    },
    copy = True,
)

_SELF_REF_SOURCE = pkgs_source(
    dep = ":self_ref_source",
    digests = ["sha256:" + sha256("\n".join(["configure"] + _SELF_REF_CONFIGURE_CONTENT))],
)

pkgs_configure_make_install_package(
    name = "self_ref_consumer",
    package_name = "self-ref-consumer",
    version = "0",
    sources = [_SELF_REF_SOURCE],
    configure_args = [
        pkgs_self_store_path("--self-path="),
    ],
    native_build_inputs = [
        "//bootstrap/foreign_seed:coreutils",
        "//bootstrap/foreign_seed:gnumake",
    ],
)

_FAILED_CONSUMER_MAKEFILE_CONTENT = [
    "all:",
    "\t:",
    "install:",
    "\tfalse",
]

write_file(
    name = "failed_consumer_makefile",
    out = "Makefile",
    content = _FAILED_CONSUMER_MAKEFILE_CONTENT,
)

filegroup(
    name = "failed_consumer_source",
    srcs = {
        "Makefile": ":failed_consumer_makefile",
    },
    copy = True,
)

_FAILED_CONSUMER_SOURCE = pkgs_source(
    dep = ":failed_consumer_source",
    digests = ["sha256:" + sha256("\n".join(["Makefile"] + _FAILED_CONSUMER_MAKEFILE_CONTENT))],
)

pkgs_make_install_package(
    name = "failed_consumer",
    package_name = "failed-consumer",
    version = "0",
    sources = [_FAILED_CONSUMER_SOURCE],
    native_build_inputs = [
        "//bootstrap/foreign_seed:coreutils",
        "//bootstrap/foreign_seed:gnumake",
    ],
)

_FINAL_BASE = [
    "//development/libraries/glibc:out_stage1",
    "//development/tools/misc/binutils:bin_stage1",
    "//development/compilers/gcc:out_stage2",
    "//development/tools/build-managers/gnumake:bin_final",
    "//shells/bash:bin_final",
    "//tools/archivers/gnutar:bin",
    "//tools/compression/bzip2:bin",
    "//tools/compression/gzip:out",
    "//tools/misc/coreutils:bin_final",
    "//tools/misc/findutils:bin_final",
    "//tools/text/diffutils:bin",
    "//tools/text/gawk:bin_final",
    "//tools/text/gnugrep:bin_final",
    "//tools/text/gnupatch:bin_final",
    "//tools/text/gnused:bin_final",
]

_FOREIGN_SEED = [
    "//bootstrap/foreign_seed:bash",
    "//bootstrap/foreign_seed:gnumake",
    "//bootstrap/foreign_seed:gcc",
    "//bootstrap/foreign_seed:binutils",
    "//bootstrap/foreign_seed:coreutils",
    "//bootstrap/foreign_seed:gnused",
    "//bootstrap/foreign_seed:gnugrep",
    "//bootstrap/foreign_seed:gawk",
    "//bootstrap/foreign_seed:gnum4",
    "//bootstrap/foreign_seed:bison",
    "//bootstrap/foreign_seed:gettext",
    "//bootstrap/foreign_seed:python3",
    "//bootstrap/foreign_seed:gnutar",
    "//bootstrap/foreign_seed:gzip",
    "//bootstrap/foreign_seed:patch",
    "//bootstrap/foreign_seed:diffutils",
    "//bootstrap/foreign_seed:findutils",
]

pkgs_seed_free(
    name = "zlib_out_seed_free",
    packages = ["//development/libraries/zlib:out"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "zstd_lib_seed_free",
    packages = ["//tools/compression/zstd:lib"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "lz4_lib_seed_free",
    packages = ["//tools/compression/lz4:lib"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "ncurses_lib_seed_free",
    packages = ["//development/libraries/ncurses:lib"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "readline_lib_seed_free",
    packages = ["//development/libraries/readline:lib"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "gnum4_bin_seed_free",
    packages = ["//development/tools/misc/gnum4:bin"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "perl_bin_seed_free",
    packages = ["//development/interpreters/perl:bin"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "bison_bin_seed_free",
    packages = ["//development/tools/parsing/bison:bin"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "flex_bin_seed_free",
    packages = ["//development/tools/parsing/flex:bin"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "postgresql_lib_seed_free",
    packages = ["//servers/sql/postgresql:lib"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "postgresql_bin_seed_free",
    packages = ["//servers/sql/postgresql:bin"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "postgresql_dev_seed_free",
    packages = ["//servers/sql/postgresql:dev"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "libcap_lib_seed_free",
    packages = ["//development/libraries/libcap:lib"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "libcap_dev_seed_free",
    packages = ["//development/libraries/libcap:dev"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "bubblewrap_bin_seed_free",
    packages = ["//tools/sandboxing/bubblewrap:bin"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "gnugrep_bin_seed_free",
    packages = ["//tools/text/gnugrep:bin"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "gawk_bin_seed_free",
    packages = ["//tools/text/gawk:bin"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "gnupatch_bin_seed_free",
    packages = ["//tools/text/gnupatch:bin"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "python_build_interpreter_seed_free",
    packages = ["//development/interpreters/python:build_interpreter"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "ninja_bin_seed_free",
    packages = ["//development/tools/build-managers/ninja:bin"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "meson_bin_seed_free",
    packages = ["//development/tools/build-managers/meson:bin"],
    forbidden = _FOREIGN_SEED,
)

pkgs_seed_free(
    name = "inih_out_seed_free",
    packages = ["//development/libraries/inih:out"],
    forbidden = _FOREIGN_SEED,
)

pkgs_foreign_build_free(
    name = "inih_native_graph_foreign_build_free",
    packages = ["//development/libraries/inih:out"],
)

pkgs_seed_free(
    name = "final_base_seed_free",
    packages = _FINAL_BASE,
    forbidden = _FOREIGN_SEED,
)

pkgs_elf_interpreters(
    name = "final_base_pkgs_interpreters",
    packages = _FINAL_BASE,
    interpreter = "//development/libraries/glibc:out_stage1",
    interpreter_relpath = "lib/ld-linux-x86-64.so.2",
)
