load("//rules:toolchains.bzl", "pkgs_bootstrap_rust_binary")

_COMMON_SRCS = [
    "src/common.rs",
]

_BUILD_SRCS = _COMMON_SRCS + [
    "src/build.rs",
]

_COMMON_DEPS = [
    "//third-party/rust:clap",
    "//third-party/rust:libc",
    "//third-party/rust:tempfile",
    "//third-party/rust:thiserror",
]

_STORE_SUBSTITUTE_SRCS = _COMMON_SRCS + [
    "src/store_substitute.rs",
]

_STORE_SUBSTITUTE_DEPS = _COMMON_DEPS + [
    "//third-party/rust:serde",
    "//third-party/rust:serde_json",
    "//third-party/rust:sha2",
]

pkgs_bootstrap_rust_binary(
    name = "pkgs_configure_make_install",
    srcs = _BUILD_SRCS + [
        "src/bin/pkgs_configure_make_install.rs",
        "src/configure_make_install.rs",
    ],
    crate_root = "src/bin/pkgs_configure_make_install.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_meson_install",
    srcs = _BUILD_SRCS + [
        "src/bin/pkgs_meson_install.rs",
        "src/meson_install.rs",
    ],
    crate_root = "src/bin/pkgs_meson_install.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_make_install",
    srcs = _BUILD_SRCS + [
        "src/bin/pkgs_make_install.rs",
        "src/make_install.rs",
    ],
    crate_root = "src/bin/pkgs_make_install.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_linux_headers_install",
    srcs = _COMMON_SRCS + [
        "src/bin/pkgs_linux_headers_install.rs",
        "src/linux_headers_install.rs",
    ],
    crate_root = "src/bin/pkgs_linux_headers_install.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_compose_sources",
    srcs = _COMMON_SRCS + [
        "src/bin/pkgs_compose_sources.rs",
        "src/compose_sources.rs",
    ],
    crate_root = "src/bin/pkgs_compose_sources.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_stage_tree",
    srcs = _COMMON_SRCS + [
        "src/bin/pkgs_stage_tree.rs",
        "src/stage_tree.rs",
    ],
    crate_root = "src/bin/pkgs_stage_tree.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_export_store_object",
    srcs = _STORE_SUBSTITUTE_SRCS + [
        "src/bin/pkgs_export_store_object.rs",
    ],
    crate_root = "src/bin/pkgs_export_store_object.rs",
    visibility = ["PUBLIC"],
    deps = _STORE_SUBSTITUTE_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_hydrate_store_object",
    srcs = _STORE_SUBSTITUTE_SRCS + [
        "src/bin/pkgs_hydrate_store_object.rs",
    ],
    crate_root = "src/bin/pkgs_hydrate_store_object.rs",
    visibility = ["PUBLIC"],
    deps = _STORE_SUBSTITUTE_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_import_store_object",
    srcs = _STORE_SUBSTITUTE_SRCS + [
        "src/bin/pkgs_import_store_object.rs",
    ],
    crate_root = "src/bin/pkgs_import_store_object.rs",
    visibility = ["PUBLIC"],
    deps = _STORE_SUBSTITUTE_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_export_store_closure",
    srcs = _STORE_SUBSTITUTE_SRCS + [
        "src/bin/pkgs_export_store_closure.rs",
    ],
    crate_root = "src/bin/pkgs_export_store_closure.rs",
    visibility = ["PUBLIC"],
    deps = _STORE_SUBSTITUTE_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_hydrate_store_closure",
    srcs = _STORE_SUBSTITUTE_SRCS + [
        "src/bin/pkgs_hydrate_store_closure.rs",
    ],
    crate_root = "src/bin/pkgs_hydrate_store_closure.rs",
    visibility = ["PUBLIC"],
    deps = _STORE_SUBSTITUTE_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_project_hydrated_store_object",
    srcs = _STORE_SUBSTITUTE_SRCS + [
        "src/bin/pkgs_project_hydrated_store_object.rs",
    ],
    crate_root = "src/bin/pkgs_project_hydrated_store_object.rs",
    visibility = ["PUBLIC"],
    deps = _STORE_SUBSTITUTE_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_verify_hydrated_store_object",
    srcs = _STORE_SUBSTITUTE_SRCS + [
        "src/bin/pkgs_verify_hydrated_store_object.rs",
    ],
    crate_root = "src/bin/pkgs_verify_hydrated_store_object.rs",
    visibility = ["PUBLIC"],
    deps = _STORE_SUBSTITUTE_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_verify_no_refs",
    srcs = _COMMON_SRCS + [
        "src/bin/pkgs_verify_no_refs.rs",
        "src/verify_no_refs.rs",
    ],
    crate_root = "src/bin/pkgs_verify_no_refs.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_verify_elf_interpreters",
    srcs = _COMMON_SRCS + [
        "src/bin/pkgs_verify_elf_interpreters.rs",
        "src/verify_elf_interpreters.rs",
    ],
    crate_root = "src/bin/pkgs_verify_elf_interpreters.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_verify_reproducible_tree",
    srcs = _COMMON_SRCS + [
        "src/bin/pkgs_verify_reproducible_tree.rs",
        "src/verify_reproducible_tree.rs",
    ],
    crate_root = "src/bin/pkgs_verify_reproducible_tree.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_verify_archive_metadata",
    srcs = _COMMON_SRCS + [
        "src/bin/pkgs_verify_archive_metadata.rs",
        "src/verify_archive_metadata.rs",
    ],
    crate_root = "src/bin/pkgs_verify_archive_metadata.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_cc_wrapper_tree",
    srcs = _COMMON_SRCS + [
        "src/bin/pkgs_cc_wrapper_tree.rs",
        "src/cc_wrapper_tree.rs",
    ],
    crate_root = "src/bin/pkgs_cc_wrapper_tree.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)

pkgs_bootstrap_rust_binary(
    name = "pkgs_bintools_wrapper_tree",
    srcs = _COMMON_SRCS + [
        "src/bin/pkgs_bintools_wrapper_tree.rs",
        "src/bintools_wrapper_tree.rs",
    ],
    crate_root = "src/bin/pkgs_bintools_wrapper_tree.rs",
    visibility = ["PUBLIC"],
    deps = _COMMON_DEPS,
)
