load("//bootstrap:island_visibility.bzl", "BOOTSTRAP_PRODUCER_VISIBILITY")
load("//rules:pkgs.bzl", "pkgs_configure_make_install_package", "pkgs_http_archive_source", "pkgs_seed_cut", "pkgs_seed_free")

_SOURCE = pkgs_http_archive_source(
    name = "source",
    sha256 = "f87cee69eec2b4fcbf60a396b030ad6aa3415f192aa5f7ee84cad5e11f7f5ae3",
    strip_prefix = "patch-2.8",
    urls = ["https://ftp.nluug.nl/pub/gnu/patch/patch-2.8.tar.xz"],
)

_NATIVE_TOOLS = [
    "//shells/bash:bin_stage0",
    "//tools/text/gnused:bin_stage0",
    "//tools/text/gnugrep:bin_stage0",
    "//bootstrap/foreign_seed:gnumake",
    "//bootstrap/foreign_seed:gcc",
    "//bootstrap/foreign_seed:binutils",
    "//bootstrap/foreign_seed:coreutils",
    "//bootstrap/foreign_seed:findutils",
    "//bootstrap/foreign_seed:gawk",
]

_FINAL_NATIVE_TOOLS = [
    "//shells/bash:bin_stage2",
    "//development/tools/build-managers/gnumake:bin_stage0",
    "//development/tools/misc/binutils:bin_stage1_wrapped",
    "//development/compilers/gcc:bin_stage2",
    "//tools/misc/coreutils:bin_stage0",
    "//tools/misc/findutils:bin_stage0",
    "//tools/text/gawk:bin_stage0",
    "//tools/text/gnugrep:bin_stage0",
    "//tools/text/gnupatch:bin_stage0",
    "//tools/text/gnused:bin_stage0",
]

_PKGS_NATIVE_TOOLS = [
    "//shells/bash:bin",
    "//development/tools/build-managers/gnumake:bin",
    "//development/tools/misc/binutils:bin",
    "//development/compilers/gcc:bin",
    "//tools/misc/coreutils:bin",
    "//tools/misc/findutils:bin",
    "//tools/text/gawk:bin",
    "//tools/text/gnugrep:bin",
    "//tools/text/gnused:bin",
]

_FOREIGN_SEED = [
    "//bootstrap/foreign_seed:bash",
    "//bootstrap/foreign_seed:gnumake",
    "//bootstrap/foreign_seed:gcc",
    "//bootstrap/foreign_seed:binutils",
    "//bootstrap/foreign_seed:coreutils",
    "//bootstrap/foreign_seed:gnused",
    "//bootstrap/foreign_seed:gnugrep",
    "//bootstrap/foreign_seed:gawk",
    "//bootstrap/foreign_seed:gnum4",
    "//bootstrap/foreign_seed:bison",
    "//bootstrap/foreign_seed:gettext",
    "//bootstrap/foreign_seed:python3",
    "//bootstrap/foreign_seed:gnutar",
    "//bootstrap/foreign_seed:gzip",
    "//bootstrap/foreign_seed:patch",
    "//bootstrap/foreign_seed:diffutils",
    "//bootstrap/foreign_seed:findutils",
]

pkgs_configure_make_install_package(
    name = "bin_stage0",
    package_name = "patch",
    version = "2.8",
    sources = [_SOURCE],
    configure_env = ["CC=cc"],
    native_build_inputs = _NATIVE_TOOLS,
    visibility = BOOTSTRAP_PRODUCER_VISIBILITY,
)

pkgs_seed_free(
    name = "bin_stage0_seed_free",
    packages = [":bin_stage0"],
    forbidden = [
        "//bootstrap/foreign_seed:gnumake",
        "//bootstrap/foreign_seed:gcc",
        "//bootstrap/foreign_seed:binutils",
        "//bootstrap/foreign_seed:coreutils",
        "//bootstrap/foreign_seed:findutils",
        "//bootstrap/foreign_seed:gawk",
    ],
    visibility = BOOTSTRAP_PRODUCER_VISIBILITY,
)

pkgs_configure_make_install_package(
    name = "bin_final",
    package_name = "patch",
    version = "2.8",
    sources = [_SOURCE],
    configure_env = ["CC=cc"],
    native_build_inputs = _FINAL_NATIVE_TOOLS,
    runtime_inputs = ["//development/libraries/glibc:out_stage1"],
    visibility = BOOTSTRAP_PRODUCER_VISIBILITY,
)

pkgs_configure_make_install_package(
    name = "bin_promoted",
    package_name = "patch",
    version = "2.8",
    sources = [_SOURCE],
    configure_env = ["CC=cc"],
    native_build_inputs = _PKGS_NATIVE_TOOLS,
    runtime_inputs = [
        "//development/compilers/gcc:out",
        "//development/libraries/glibc:out",
    ],
    visibility = BOOTSTRAP_PRODUCER_VISIBILITY,
)

pkgs_seed_cut(
    name = "bin_promoted_seed_cut",
    package = ":bin_promoted",
    forbidden = _FOREIGN_SEED,
    visibility = BOOTSTRAP_PRODUCER_VISIBILITY,
)

alias(
    name = "bin",
    actual = "//bootstrap/substitutes:gnupatch",
    visibility = ["PUBLIC"],
)

pkgs_seed_free(
    name = "bin_final_seed_free",
    packages = [":bin_final"],
    forbidden = [
        "//bootstrap/foreign_seed:gnumake",
        "//bootstrap/foreign_seed:gcc",
        "//bootstrap/foreign_seed:binutils",
        "//bootstrap/foreign_seed:coreutils",
        "//bootstrap/foreign_seed:findutils",
        "//bootstrap/foreign_seed:gawk",
    ],
    visibility = BOOTSTRAP_PRODUCER_VISIBILITY,
)
