load("//rules:pkgs.bzl", "pkgs_export_store_closure", "pkgs_export_store_substitute")

pkgs_export_store_substitute(
    name = "gmp",
    package = "//development/libraries/gmp:out_final",
)

pkgs_export_store_substitute(
    name = "mpfr",
    package = "//development/libraries/mpfr:out_final",
)

pkgs_export_store_substitute(
    name = "libmpc",
    package = "//development/libraries/libmpc:out_final",
)

pkgs_export_store_substitute(
    name = "glibc",
    package = "//development/libraries/glibc:out_stage1",
)

pkgs_export_store_substitute(
    name = "gcc",
    package = "//development/compilers/gcc:out_stage2",
)

pkgs_export_store_substitute(
    name = "binutils",
    package = "//development/tools/misc/binutils:bin_stage1",
)

pkgs_export_store_substitute(
    name = "bash",
    package = "//shells/bash:bin_final",
)

pkgs_export_store_substitute(
    name = "gnumake",
    package = "//development/tools/build-managers/gnumake:bin_final",
)

pkgs_export_store_substitute(
    name = "coreutils",
    package = "//tools/misc/coreutils:bin_final",
)

pkgs_export_store_substitute(
    name = "findutils",
    package = "//tools/misc/findutils:bin_final",
)

pkgs_export_store_substitute(
    name = "gnused",
    package = "//tools/text/gnused:bin_final",
)

pkgs_export_store_substitute(
    name = "binutils_wrapper",
    package = "//development/tools/misc/binutils:bin_final_wrapped",
)

pkgs_export_store_substitute(
    name = "linux_headers",
    package = "//os-specific/linux/kernel-headers:out_final",
)

pkgs_export_store_substitute(
    name = "gcc_wrapper",
    package = "//development/compilers/gcc:bin_final",
)

pkgs_export_store_closure(
    name = "linux_x86_64_bundle",
    closure_name = "bootstrap-linux-x86_64",
    roots = [
        ":binutils_wrapper",
        ":coreutils",
        ":findutils",
        ":gcc_wrapper",
        ":gnumake",
        ":gnused",
    ],
    objects = [
        ":bash",
        ":binutils",
        ":binutils_wrapper",
        ":coreutils",
        ":findutils",
        ":gcc",
        ":gcc_wrapper",
        ":glibc",
        ":gmp",
        ":gnumake",
        ":gnused",
        ":libmpc",
        ":linux_headers",
        ":mpfr",
    ],
    visibility = ["PUBLIC"],
)
