# Generated by pkgs-add-cas-manifest; review before pinning.
PIN = {
    "canonical_tree_hash": "sha256:4e3627f9a8f6e52152ff238d96a99c8eb55789a9a94c9bd29bffbe9d421bf2e7",
    "cas_root_digest": "7023ce78169ae2fe5526976e0bc22b53e885c33715e9614bef69c411bc9995e9:79",
}
